# Generated by Django 4.1.1 on 2022-09-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                ("arenas_counted", models.IntegerField(null=True)),
                ("score_1", models.IntegerField()),
                ("score_2", models.IntegerField(null=True)),
                ("score_3", models.IntegerField(null=True)),
                ("score_4", models.IntegerField(null=True)),
                ("score_5", models.IntegerField(null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
                    ),
                ),
            ],
        ),
    ]
