# Generated by Django 4.1.1 on 2022-09-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ArenaInBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "arena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="arenas.arena"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tournaments.division"
                    ),
                ),
            ],
        ),
    ]
